#!/bin/sh

set -e

case "$1" in
    upgrade) ;;
    remove|failed-upgrade|deconfigure)
        update-alternatives --remove moc "/opt/qt4-qws/bin/moc-qt4"
        update-alternatives --remove uic "/opt/qt4-qws/bin/uic-qt4"
        update-alternatives --remove lupdate "/opt/qt4-qws/bin/lupdate-qt4"
        update-alternatives --remove lrelease "/opt/qt4-qws/bin/lrelease-qt4"
        ;;
esac

#DEBHELPER#
